### ISSUE TITLE
Get the value of the additional checkbox?

### ISSUE THREAD

**Issue by mbooh** [Geta/Klarna#39]
Hi!

I can't figure out how to get the value of the additional checkbox?
The checkbox is shown just fine if I add a value in the Commerce Manager settings but how do I retrieve it?

In your v2 version you had this:

`public bool IsNewsletterChecked(string orderId)
        {
            if (orderId == null) throw new ArgumentNullException("orderId");

            var order = FetchOrder(orderId);
            var request = order.GetValue("merchant_requested") as JObject;
            if (request != null)
            {
                return request["additional_checkbox"].ToObject<bool>();
            }
            return false;
        }
`

Maybe I'm just missing something here?

Thanks!

/Kristoffer

**Comment by mbooh** [comment]
I think I found some documentation:

[https://developers.klarna.com/api/#checkout-api__order__merchant_requested](url)

I'm happy to fix this but I'm not sure how to use the information. Could someone please guide me?

`"merchant_requested": {
        "additional_checkbox": false,
        "additional_checkboxes": [
            {
                "id": "string",
                "checked": false
            }
        ]
    },
`
Thanks!

**Comment by marisks** [comment]
In KCO v3 we are using Klarna's library and it doesn't have this feature. Here is what they have:
https://github.com/klarna/kco_rest_dotnet/blob/v2.2/Klarna.Rest/Klarna.Rest/Models/CheckoutOrderData.cs

**Comment by mbooh** [comment]
Now that is strange!
The have settings for adding a checkbox but no way of retrieving the data?!

Do you have any technical contact at Klarna that you use or is it just the normal technical support that you use?

Thanks again!

Skickat från min iPhone

29 aug. 2018 kl. 16:21 skrev Māris Krivtežs <notifications@github.com<mailto:notifications@github.com>>:


In KCO v3 we are using Klarna's library and it doesn't have this feature. Here is what they have:
https://github.com/klarna/kco_rest_dotnet/blob/v2.2/Klarna.Rest/Klarna.Rest/Models/CheckoutOrderData.cs

**Comment by marisks** [comment]
I have created an issue on Klarna repo.

**Comment by kristibarbosky** [comment]
@mbooh @marisks - Unfortunately Klarna has not been updating the SDK's.  Klarna is reviewing the SDK's and the SDK's will likely be redone (but it will be a new SDK, not an update of these current SDK's).  We don't have committed timelines for the new SDK's at this time.  

Unfortunately the best approach is likely for you to directly update your own local SDK copy if necessary to allow retrieving the additional checkbox data.

**Comment by mbooh** [comment]
Perfect, thanks!

Skickat från min iPhone

29 aug. 2018 kl. 16:39 skrev Māris Krivtežs <notifications@github.com<mailto:notifications@github.com>>:


I have created an issue on Klarna repo.

**Comment by kristibarbosky** [comment]
Thanks for the update @mbooh - glad you're able to make progress!  I don't believe that the PR will be processed directly as the Klarna team is looking to generate Klarna SDK's with a new process going forward.

**Comment by frederikvig** [comment]
Closing because of age.
