### ISSUE TITLE
Parameters tab is has empty values after reopening

### ISSUE THREAD

**Issue by srorije** [Geta/Klarna#41]
I'm using Klarna.Checkout.v3 version 1.1.0 because we are still on Episerver 11. In Commerce Manager, I can add the KlarnaCheckout payment method. In the Parameters tab I fill in the required settings. However when I press OK and open this tab again, all the values are empty. 
Note: when I open the PaymentMethodParameter table in the Commerce database, I see a row with Parameter=_KlarnaSerializedMarketOptions and a Value that seems to be ok.
This issue is related to the language that you select for the payment method. If you select the language that is currently active (as far as a language can be 'active' in Episerver, I'm a beginner at Episerver) the the issue does not occur. However when you select another language, the issue occurs.

**Comment by marisks** [comment]
I think the easiest way for you would be forking the repo and fixing the issue for you. 
This version is the latest for Episerver 11: https://github.com/Geta/Klarna/tree/release-1.0.59
And this is a fix which solved the issue in Episerver 12: https://github.com/Geta/Klarna/commit/9c96872e715652681b2d9695cd9a6c92a78815c6

**Comment by srorije** [comment]
Thanks marisks for the info. I think I understand what you mean. However I'm struggling how to do that in practice. Meanwhile I clicked "Fork" in GitHub. And I cloned the repository in SourceTree. But am I supposed to create a branch origin/issue/41 in SourceTree? And how can I create a new package version 1.1.1 instead of version 2.0.2? I would appreciate any kind of help.

**Comment by marisks** [comment]
You have to checkout origin/issue/41. Not sure how it can be done in SourceTree.

Then there is a pack.bat script for packaging: https://github.com/Geta/Klarna/blob/master/src/pack.bat
You will need a nuget.exe in the environment path to run it.
And you can change the version in an AssemblyInfo.cs file. You have to do it for all projects.

**Comment by frederikvig** [comment]
Closing issue since this is fixed in latest version.
