### ISSUE TITLE
Issue when using DXC with Cloudflare

### ISSUE THREAD

**Issue by jacobrastad** [Geta/Klarna#43]
This is more of a suggestion for addition to the README.

We had issues with orders not getting through because Klarna's call to the **validation url** was blocked by Cloudflare.

When trying to call them manually we got presented with a captcha page, which in turn resulted in orders being blocked in the checkout.

I would suggest to add a section to the README about DXC / Cloudflare and a recommendation to turn off the WAF for the URLs to klarnacheckoutapi (or the URL that you're using).

**Comment by frederikvig** [comment]
Thanks for reporting this. Note has been added to readme.
