### ISSUE TITLE
Klarna Checkout clears Line items from cart

### ISSUE THREAD

**Issue by niklaslund** [Geta/Klarna#48]
Hi!

Im having some troubles with creating the Klarna checkout widget. In my checkout-controller i run _klarnaCheckoutService.CreateOrUpdateOrder(cart), but when this is run
I can see that all my Line items are removed from my cart in epi, the cart still remains though but without any values.
Everything looks good when I check playground and the widget is generated with correct values so the line items are removed after sending it to Klarna. 
However, if I leave this page or reload the checkout page, I get an "empty cart" warning from Klarna.
Do you have any idea why this is happening?

Also, at first when I ran "_klarnaCheckoutService.CreateOrUpdateOrder(cart)" it casted a NullReferenceException because of this :

var shipment = cart.GetFirstShipment();
if (shipment.ShippingAddress != null)
{
	orderData.ShippingAddress = shipment.ShippingAddress.ToAddress();
}

in "CreateOrder(ICart cart)"
So I had to add a new Shipment for this to work :

"cart.AddShipment(new Shipment {OrderFormId = cart.OrderForms.First().OrderFormId });"

Any help would be appreciated.

**Comment by marisks** [comment]
As I remember, you should call _klarnaCheckoutService.CreateOrUpdateOrder(cart) on checkout when you finish it. So the checkout is finished and you should not have anything in the cart and start a new "cart session".

**Comment by marisks** [comment]
Regarding shipments, it seems that you are not using new APIs. Episerver makes sure that you always have at least one OrderForm and one Shipment if APIs are properly used.

Which version of Episerver CMS, Commerce and Klarna do you have?

**Comment by frederikvig** [comment]
Closing because of age.
