### ISSUE TITLE
The readme file is outdated

### ISSUE THREAD

**Issue by vietanh-epi** [Geta/Klarna#54]
Hi,
I found that some points in the readme file are outdated.
For example:
**Return KlarnaViewModel in PaymentMethodViewModelResolver** under "Quicksilver demo site implementation"
When clicking the link, I got "404 not found" error. The same for some other links.

Could you please help on this?

Thanks and regards,
/Viet Anh

**Comment by uyenpp** [comment]
I list here some links https://github.com/Geta/Klarna/blob/master/demo/Sources/EPiServer.Reference.Commerce.Site/Views/Shared/_KlarnaPaymentsPaymentMethod.cshtml 
https://github.com/Geta/Klarna/blob/master/demo/Sources/EPiServer.Reference.Commerce.Site/Features/Payment/ViewModels/KlarnaPaymentsViewModel.cs
https://github.com/Geta/Klarna/blob/master/demo/Sources/EPiServer.Reference.Commerce.Site/Features/Payment/ViewModels/PaymentMethodViewModelResolver.cs
https://github.com/Geta/Klarna/blob/master/demo/Sources/EPiServer.Reference.Commerce.Site/Scripts/js/Checkout.Klarna.js

**Comment by frederikvig** [comment]
Thanks, we've updated the URLs now.
