### ISSUE TITLE
Update deprecated package Klarna.Rest to Klarna.Rest.Core

### ISSUE THREAD

**Issue by Sebbe** [Geta/Klarna#58]
As described here https://github.com/klarna/kco_dotnet the package you use now is deprecated and should instead use Klarna.Rest.Core https://github.com/klarna/kco_rest_dotnet

**Comment by frederikvig** [comment]
Thanks for reporting this Sebastian.

**Comment by boremalm** [comment]
@Sebbe Im working on that over here: https://github.com/boremalm/Klarna in case you feel like helping out :)

**Comment by frederikvig** [comment]
Fixed in version 3.0.1
