### ISSUE TITLE
Nuget package without Klarna.Rest.Core ref

### ISSUE THREAD

**Issue by LucGosso** [Geta/Klarna#84]
Hi Guys! When will you release a version on episerver nuget feed without the dependecy to deprecated Klarna.Rest.Core ? seems that you are working on it :)

**Comment by frederikvig** [comment]
Should be soon now! Currently being tested by Klarna

**Comment by frederikvig** [comment]
Fixed in version 3.5.0 - https://github.com/Geta/Klarna/blob/master/CHANGELOG.md#350. Currently going through Episerver addon review process.

**Comment by frederikvig** [comment]
Released on nuget.episerver.com
