### ISSUE TITLE
New order created instead of updated

### ISSUE THREAD

**Issue by hyllengren** [Geta/Klarna#92]
It seems like there is an issue in https://github.com/Geta/Klarna/blob/a118814d229091a5ee350546770cba2d8b93dfc3/src/Klarna.Checkout/KlarnaCheckoutService.cs#L148

UpdateOrder takes string orderId, but is not used anywhere. In the old refit implementation, this was sent in the POST to Klarna.

Now, the OrderId from the CheckoutOrder object is sent in the request instead. But this is never set, seems like orderId from cart should be set in UpdateOrder or possible GetCheckoutOrderData

**Comment by frederikvig** [comment]
You can see the call and logic in the CreateOrUpdateOrder method. OrderId is from the Episerver cart custom property KlarnaCheckoutOrderIdCart. Or are you maybe referring to something else since you mention refit?

**Comment by hyllengren** [comment]
Yes but orderId is never used in the UpdateOrder method.

https://github.com/Geta/Klarna/blob/a118814d229091a5ee350546770cba2d8b93dfc3/src/Klarna.Checkout/LoggingCheckoutOrder.cs#L38
Takes just CheckoutOrderData as paramater

`        
public async Task<CheckoutOrder> UpdateOrder(CheckoutOrder order)
{
    var url = ApiUrlHelper.GetApiUrlForController(ApiSession.ApiUrl, ApiControllerUri, order.OrderId);
    return await Post<CheckoutOrder>(url, order).ConfigureAwait(false);
}
`
Uses order.OrderId in the call to klarna. But the orderId of CheckoutOrderData is not set within the UpdateOrder method, which leads to Klarna returning a new order every time, and not updating the existing one.

I had to set orderId in a ICheckoutOrderDataBuilder which solved the problem for me

**Comment by frederikvig** [comment]
Thanks - fixed now in version 3.5.2 (should be out on the feed soon).
