### ISSUE TITLE
Saving configuration options and various markets/languages

### ISSUE THREAD

**Issue by frederikvig** [Geta/klarna#94]
The issue seems related to "market" dropdown which prevents parameters' values being saved correctly.

## How to reproduce:

1. Enter all required parameters
2. Save changes
3. Open "KlarnaPayments", navigate to parameters tab, all values are gone.

## Workaround

1. Enter all required parameters, then navigate to **market** tab, and select one market
2. Save changes
3. Open "KlarnaPayments", navigate to parameters tab, this time you'll be able to see market dropdown is set with selected value set from last step, but all other mandatory values are gone. Re-enter them again, and save changes, this time other mandatory values will be persisted.

P.s I'm not sure whats the real value of market dropdown under parameters tab as market is part part of payment plugin and can be configured via market tab.

Let me know if you need any further information.

_Originally posted by @javafun

**Comment by Sebbe** [comment]
Hi, we saw the same issue for one of our markets where it refused to save, but when looking in the DB it looks like it actualy did save.
We had changed the default landuage for the market from swedish to english, and it was then we couldn't save the configurment for that market. We changed it back to default language swedish, and it started working again. Really weird.

**Comment by frederikvig** [comment]
Closing since version 4.0.0 and later has the configuration in appsettings.json instead of CM.
